### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by deyhle** [tovazm/superagent-binary-parser#3]
Could you please publish the latest pull requests to npm? I was still getting the buggy first version via `npm install`. Thank you very much!

**Comment by jackspaniel** [comment]
Argh - that was a fun one to figure out. I kept pasting the code from github and not getting that weird error - didn't realize it didn't match npm. Since this repo is dead apparently I'm just going to pluck the code. It's too minimal to fork.

**Comment by watsoncj** [comment]
Also got tripped up by the version from npm which inserts text `undefined` at the front of the buffer. Otherwise, great module!

**Comment by abelcha** [comment]
New version have been published to npm
